<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35577" started-at="2022-01-21T16:35:37 GMT-08:00" finished-at="2022-01-21T16:36:12 GMT-08:00">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35577" started-at="2022-01-21T16:35:37 GMT-08:00" finished-at="2022-01-21T16:36:12 GMT-08:00">
      <class name="ExceHandling.LoginActitimewithexcel">
        <test-method status="PASS" signature="getAppData()[pri:0, instance:ExceHandling.LoginActitimewithexcel@7ce6a65d]" name="getAppData" is-config="true" duration-ms="2484" started-at="2022-01-21T16:35:37 GMT-08:00" finished-at="2022-01-21T16:35:39 GMT-08:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAppData -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:ExceHandling.LoginActitimewithexcel@7ce6a65d]" name="setUp" is-config="true" duration-ms="20251" started-at="2022-01-21T16:35:39 GMT-08:00" finished-at="2022-01-21T16:36:00 GMT-08:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginIntoActitimeApp()[pri:0, instance:ExceHandling.LoginActitimewithexcel@7ce6a65d]" name="loginIntoActitimeApp" duration-ms="12532" started-at="2022-01-21T16:36:00 GMT-08:00" finished-at="2022-01-21T16:36:12 GMT-08:00">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Either Actitime home page title got changed or page is not loaded properly expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Either Actitime home page title got changed or page is not loaded properly expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at ExceHandling.LoginActitimewithexcel.loginIntoActitimeApp(LoginActitimewithexcel.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginIntoActitimeApp -->
      </class> <!-- ExceHandling.LoginActitimewithexcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
